package matrixTest.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Matrix = 0;
  public static final int MatrixRow = 1;
  public static final int MyRoot = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xde0c68e0feb84120L, 0xb3030529bea9f26bL);
    builder.put(0x1f8aaef472eeaf41L, Matrix);
    builder.put(0x1f8aaef472eeaf53L, MatrixRow);
    builder.put(0x1f8aaef472eec3c7L, MyRoot);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
